# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bijection Vector
#'
#' @param K number of levels
#' @return A \code{vec} with length \eqn{K}.
#' @export
bijectionvector <- function(K) {
    .Call('_ecdmcore_bijectionvector', PACKAGE = 'ecdmcore', K)
}

#' Inverse Bijection Vector
#'
#' @param CL A \code{double} that controls ...
#' @inheritParams bijectionvector
#' @return A \code{vec} with length \eqn{K}.
#' @export
inv_bijectionvector <- function(K, CL) {
    .Call('_ecdmcore_inv_bijectionvector', PACKAGE = 'ecdmcore', K, CL)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_ecdmcore_RcppExport_registerCCallable', PACKAGE = 'ecdmcore')
})
